In [2]:
%load_ext sql

In [3]:
%sql ibm_db_sa://xsc80456:bgxwrc9rff-fw8jv@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB

'Connected: xsc80456@BLUDB'

In [4]:
%sql select TABSCHEMA, TABNAME, CREATE_TIME from syscat.tables where tabschema = 'XSC80456'

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[('XSC80456', 'CHICAGO_SOCIOECONOMIC_DATA', datetime.datetime(2019, 9, 30, 19, 25, 19, 916261)),
 ('XSC80456', 'SCHOOLS', datetime.datetime(2019, 9, 30, 19, 41, 56, 411442)),
 ('XSC80456', 'INSTRUCTOR', datetime.datetime(2019, 9, 17, 21, 54, 2, 71447)),
 ('XSC80456', 'INTERNATIONAL_STUDENT_TEST_SCORES', datetime.datetime(2019, 9, 17, 22, 10, 29, 931390)),
 ('XSC80456', 'EMPLOYEES', datetime.datetime(2019, 8, 8, 22, 1, 14, 959796)),
 ('XSC80456', 'JOB_HISTORY', datetime.datetime(2019, 8, 8, 22, 1, 15, 116761)),
 ('XSC80456', 'LOCATIONS', datetime.datetime(2019, 8, 8, 22, 1, 15, 546692)),
 ('XSC80456', 'DEPARTMENTS', datetime.datetime(2019, 8, 8, 22, 18, 59, 382454)),
 ('XSC80456', 'JOBS', datetime.datetime(2019, 8, 8, 22, 41, 10, 856835)),
 ('XSC80456', 'PETSALE', datetime.datetime(2019, 8, 23, 4, 40, 54, 955683))]

In [5]:
%sql select * from syscat.columns where TABNAME='SCHOOLS'

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[('XSC80456', 'SCHOOLS', 'Parent_Engagement_Score', 29, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 32, "'69'", "'39'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Parent_Environment_Icon', 30, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Strong'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Parent_Environment_Score', 31, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 33, "'70'", "'36'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'AVERAGE_STUDENT_ATTENDANCE', 32, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 155, "'98.40%'", "'60.90%'", 11, None, 0, 20, 10, 1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Rate_of_Misconducts__per_100_students_', 33, 'SYSIBM  ', 'DECIMAL', 5, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 288, '+0230.6', '+0000.1', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Average_Teacher_Attendance', 34, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 55, "'98.10%'", "'91.70%'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Individualized_Education_Program_Compliance_Rate', 35, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 69, "'99.60%'", "'72.70%'", 12, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 7, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Pk_2_Literacy__', 36, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 308, "'96.3'", "'16.4'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Pk_2_Math__', 37, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 224, "'97.2'", "'10.1'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Gr3_5_Grade_Level_Math__', 38, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 336, "'98.6'", "'10'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Gr3_5_Grade_Level_Read__', 39, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 340, "'98.6'", "'10'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Gr3_5_Keep_Pace_Read__', 40, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 276, "'82.5'", "'28.8'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Gr3_5_Keep_Pace_Math__', 41, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 260, "'83.5'", "'21.7'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Gr6_8_Grade_Level_Math__', 42, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 296, "'96.5'", "'10.2'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Gr6_8_Grade_Level_Read__', 43, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 300, "'98.9'", "'100'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Gr6_8_Keep_Pace_Math_', 44, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 268, "'93.6'", "'24.3'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Gr6_8_Keep_Pace_Read__', 45, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 260, "'85.5'", "'21.4'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Gr_8_Explore_Math__', 46, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 208, "'9.7'", "'1.4'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Gr_8_Explore_Read__', 47, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 244, "'99'", "'1.4'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'ISAT_Exceeding_Math__', 48, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 297, '+100.0', '+000.6', 4, None, 0, 20, 10, 90, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'ISAT_Exceeding_Reading__', 49, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 261, '+100.0', '+000.5', 4, None, 0, 20, 10, 90, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'ISAT_Value_Add_Math', 50, 'SYSIBM  ', 'DECIMAL', 3, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 57, '+03.6', '-03.1', 3, None, 0, 20, 10, 98, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'ISAT_Value_Add_Read', 51, 'SYSIBM  ', 'DECIMAL', 3, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 60, '+04.9', '-02.8', 3, None, 0, 20, 10, 98, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'ISAT_Value_Add_Color_Math', 52, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Red'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'ISAT_Value_Add_Color_Read', 53, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Red'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Students_Taking__Algebra__', 54, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 116, "'98.5'", "'10.5'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Students_Passing__Algebra__', 55, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 94, "'93.3'", "'11.1'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', '9th Grade EXPLORE (2009)', 56, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 45, "'22.4'", "'11.6'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', '9th Grade EXPLORE (2010)', 57, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 51, "'22.2'", "'11.2'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', '10th Grade PLAN (2009)', 58, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 45, "'24.5'", "'12.9'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', '10th Grade PLAN (2010)', 59, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 49, "'24.7'", "'12.7'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Net_Change_EXPLORE_and_PLAN', 60, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 16, "'2.3'", "'0.5'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', '11th Grade Average ACT (2011)', 61, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 53, "'28.8'", "'13.6'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Net_Change_PLAN_and_ACT', 62, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 30, "'4.3'", "'0.3'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'College_Eligibility__', 63, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 78, "'98'", "'10.6'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Graduation_Rate__', 64, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 75, "'97.6'", "'10.3'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'College_Enrollment_Rate__', 65, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 70, "'90.7'", "'32.6'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'COLLEGE_ENROLLMENT', 66, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 444, '3320', '26', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'General_Services_Route', 67, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 20, '48', '30', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Freshman_on_Track_Rate__', 68, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 79, "'98.1'", "'37.1'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'X_COORDINATE', 69, 'SYSIBM  ', 'DECIMAL', 13, 3, None, None, None, 'Y', 0, None, None, ' ', ' ', 504, '+0001202756.093', '+0001121355.698', 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Y_COORDINATE', 70, 'SYSIBM  ', 'DECIMAL', 13, 3, None, None, None, 'Y', 0, None, None, ' ', ' ', 560, '+0001949501.716', '+0001817244.896', 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Latitude', 71, 'SYSIBM  ', 'DECIMAL', 18, 8, None, None, None, 'Y', 0, None, None, ' ', ' ', 472, '+0000000042.01709536', '+0000000041.65376037', 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Longitude', 72, 'SYSIBM  ', 'DECIMAL', 18, 8, None, None, None, 'Y', 0, None, None, ' ', ' ', 566, '-0000000087.53301251', '-0000000087.82933190', 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'COMMUNITY_AREA_NUMBER', 73, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 77, '76', '2', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'COMMUNITY_AREA_NAME', 74, 'SYSIBM  ', 'VARCHAR', 22, 0, 'OCTETS', 22, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 77, "'WEST TOWN'", "'ARCHER HEIGHTS'", 16, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 11, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Ward', 75, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 50, '49', '2', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Police_District', 76, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 23, '24', '2', 3, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Location', 77, 'SYSIBM  ', 'VARCHAR', 27, 0, 'OCTETS', 27, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 536, "'(42.01709536, -87.67779928)'", "'(41.65376037, -87.61434156)'", 32, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 27, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'School_ID', 0, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 566, '610543', '609674', 5, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'NAME_OF_SCHOOL', 1, 'SYSIBM  ', 'VARCHAR', 65, 0, 'OCTETS', 65, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 566, "'Woodlawn Community Elementary Sch'", "'Abraham Lincoln Elementary School'", 41, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 36, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Elementary, Middle, or High School', 2, 'SYSIBM  ', 'VARCHAR', 2, 0, 'OCTETS', 2, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 3, "'MS'", "'ES'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'Street_Address', 3, 'SYSIBM  ', 'VARCHAR', 30, 0, 'OCTETS', 30, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 566, "'9912 S Avenue H'", "'10015 S Leavitt St'", 22, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 17, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'City', 4, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 1, "'Chicago'", "'Chicago'", 12, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 7, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('XSC80456', 'SCHOOLS', 'State', 5, 'SYSIBM  ', 'VARCHAR', 2, 0, 'OCTETS', 2, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 1, "'IL'", "'IL'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),

In [6]:
%sql select distinct(colname), typename, length from syscat.columns where TABNAME='SCHOOLS'

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[('10th Grade PLAN (2009)', 'VARCHAR', 4),
 ('10th Grade PLAN (2010)', 'VARCHAR', 4),
 ('11th Grade Average ACT (2011)', 'VARCHAR', 4),
 ('9th Grade EXPLORE (2009)', 'VARCHAR', 4),
 ('9th Grade EXPLORE (2010)', 'VARCHAR', 4),
 ('AVERAGE_STUDENT_ATTENDANCE', 'VARCHAR', 6),
 ('Adequate_Yearly_Progress_Made_', 'VARCHAR', 3),
 ('Average_Teacher_Attendance', 'VARCHAR', 6),
 ('COLLEGE_ENROLLMENT', 'SMALLINT', 2),
 ('COMMUNITY_AREA_NAME', 'VARCHAR', 22),
 ('COMMUNITY_AREA_NUMBER', 'SMALLINT', 2),
 ('CPS_Performance_Policy_Level', 'VARCHAR', 15),
 ('CPS_Performance_Policy_Status', 'VARCHAR', 16),
 ('City', 'VARCHAR', 7),
 ('Collaborative_Name', 'VARCHAR', 34),
 ('College_Eligibility__', 'VARCHAR', 4),
 ('College_Enrollment_Rate__', 'VARCHAR', 4),
 ('Elementary, Middle, or High School', 'VARCHAR', 2),
 ('Environment_Icon', 'VARCHAR', 11),
 ('Environment_Score', 'SMALLINT', 2),
 ('Family_Involvement_Icon', 'VARCHAR', 11),
 ('Family_Involvement_Score', 'VARCHAR', 3),
 ('Freshman_on_Track_Rate__', 'VARCHAR', 4),
 ('General_Services_Route', 'SMALLINT', 2),
 ('Gr3_5_Grade_Level_Math__', 'VARCHAR', 4),
 ('Gr3_5_Grade_Level_Read__', 'VARCHAR', 4),
 ('Gr3_5_Keep_Pace_Math__', 'VARCHAR', 4),
 ('Gr3_5_Keep_Pace_Read__', 'VARCHAR', 4),
 ('Gr6_8_Grade_Level_Math__', 'VARCHAR', 4),
 ('Gr6_8_Grade_Level_Read__', 'VARCHAR', 4),
 ('Gr6_8_Keep_Pace_Math_', 'VARCHAR', 4),
 ('Gr6_8_Keep_Pace_Read__', 'VARCHAR', 4),
 ('Gr_8_Explore_Math__', 'VARCHAR', 4),
 ('Gr_8_Explore_Read__', 'VARCHAR', 4),
 ('Graduation_Rate__', 'VARCHAR', 4),
 ('HEALTHY_SCHOOL_CERTIFIED', 'VARCHAR', 3),
 ('ISAT_Exceeding_Math__', 'DECIMAL', 4),
 ('ISAT_Exceeding_Reading__', 'DECIMAL', 4),
 ('ISAT_Value_Add_Color_Math', 'VARCHAR', 6),
 ('ISAT_Value_Add_Color_Read', 'VARCHAR', 6),
 ('ISAT_Value_Add_Math', 'DECIMAL', 3),
 ('ISAT_Value_Add_Read', 'DECIMAL', 3),
 ('Individualized_Education_Program_Compliance_Rate', 'VARCHAR', 7),
 ('Instruction_Icon', 'VARCHAR', 11),
 ('Instruction_Score', 'SMALLINT', 2),
 ('Latitude', 'DECIMAL', 18),
 ('Leaders_Icon', 'VARCHAR', 11),
 ('Leaders_Score', 'VARCHAR', 3),
 ('Link', 'VARCHAR', 78),
 ('Location', 'VARCHAR', 27),
 ('Longitude', 'DECIMAL', 18),
 ('NAME_OF_SCHOOL', 'VARCHAR', 65),
 ('Net_Change_EXPLORE_and_PLAN', 'VARCHAR', 3),
 ('Net_Change_PLAN_and_ACT', 'VARCHAR', 3),
 ('Network_Manager', 'VARCHAR', 40),
 ('Parent_Engagement_Icon', 'VARCHAR', 7),
 ('Parent_Engagement_Score', 'VARCHAR', 3),
 ('Parent_Environment_Icon', 'VARCHAR', 7),
 ('Parent_Environment_Score', 'VARCHAR', 3),
 ('Phone_Number', 'VARCHAR', 14),
 ('Pk_2_Literacy__', 'VARCHAR', 4),
 ('Pk_2_Math__', 'VARCHAR', 4),
 ('Police_District', 'SMALLINT', 2),
 ('Rate_of_Misconducts__per_100_students_', 'DECIMAL', 5),
 ('SAFETY_SCORE', 'SMALLINT', 2),
 ('Safety_Icon', 'VARCHAR', 11),
 ('School_ID', 'INTEGER', 4),
 ('State', 'VARCHAR', 2),
 ('Street_Address', 'VARCHAR', 30),
 ('Students_Passing__Algebra__', 'VARCHAR', 4),
 ('Students_Taking__Algebra__', 'VARCHAR', 4),
 ('Teachers_Icon', 'VARCHAR', 11),
 ('Teachers_Score', 'VARCHAR', 3),
 ('Track_Schedule', 'VARCHAR', 12),
 ('Ward', 'SMALLINT', 2),
 ('X_COORDINATE', 'DECIMAL', 13),
 ('Y_COORDINATE', 'DECIMAL', 13),
 ('ZIP_Code', 'INTEGER', 4)]

##Questions

#Is the column name for the "SCHOOL ID" attribute in upper or mixed case?

mixed

What is the name of "Community Area Name" column in your table? Does it have spaces?
COMMUNITY_AREA_NAME

Are there any columns in whose names the spaces and paranthesis (round brackets) have been replaced by the underscore character "_"?

YES, ALL SPACES, PARANTHESIS REPLACED WITH _

In [7]:
#Q1

%sql select count(*) from SCHOOLS where "Elementary, Middle, or High School" = 'ES';

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[(Decimal('462'),)]

In [8]:
#Q2
%sql select max(safety_score) as "max_safety_score" from SCHOOLS;

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[(99,)]

In [9]:
#Q3

%sql select NAME_OF_SCHOOL from SCHOOLS where  (select max(safety_score) from SCHOOLS) = safety_score;

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[('Abraham Lincoln Elementary School',),
 ('Alexander Graham Bell Elementary School',),
 ('Annie Keller Elementary Gifted Magnet School',),
 ('Augustus H Burley Elementary School',),
 ('Edgar Allan Poe Elementary Classical School',),
 ('Edgebrook Elementary School',),
 ('Ellen Mitchell Elementary School',),
 ('James E McDade Elementary Classical School',),
 ('James G Blaine Elementary School',),
 ('LaSalle Elementary Language Academy',),
 ('Mary E Courtenay Elementary Language Arts Center',),
 ('Northside College Preparatory High School',),
 ('Northside Learning Center High School',),
 ('Norwood Park Elementary School',),
 ('Oriole Park Elementary School',),
 ('Sauganash Elementary School',),
 ('Stephen Decatur Classical Elementary School',),
 ('Talman Elementary School',),
 ('Wildwood Elementary School',)]

In [10]:
#Q4

%sql select NAME_OF_SCHOOL as "School Name", Average_Student_Attendance from SCHOOLS order by AVERAGE_STUDENT_ATTENDANCE desc nulls last limit 10;

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[('John Charles Haines Elementary School', '98.40%'),
 ('James Ward Elementary School', '97.80%'),
 ('Edgar Allan Poe Elementary Classical School', '97.60%'),
 ('Orozco Fine Arts & Sciences Elementary School', '97.60%'),
 ('Rachel Carson Elementary School', '97.60%'),
 ('Annie Keller Elementary Gifted Magnet School', '97.50%'),
 ('Andrew Jackson Elementary Language Academy', '97.40%'),
 ('Lenart Elementary Regional Gifted Center', '97.40%'),
 ('Disney II Magnet School', '97.30%'),
 ('John H Vanderpoel Elementary Magnet School', '97.20%')]

In [11]:
#Q5

%sql select NAME_OF_SCHOOL as "School Name", Average_Student_Attendance from SCHOOLS order by AVERAGE_STUDENT_ATTENDANCE nulls last limit 5;

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Dyett High School', '62.50%'),
 ('Wendell Phillips Academy High School', '63.00%'),
 ('Orr Academy High School', '66.30%')]

In [20]:
#Q6

%sql select NAME_OF_SCHOOL as "School Name", replace(Average_Student_Attendance,'%','') as "Average Student Attendance" from SCHOOLS order by AVERAGE_STUDENT_ATTENDANCE nulls last limit 5;

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[('Richard T Crane Technical Preparatory High School', '57.90'),
 ('Barbara Vick Early Childhood & Family Center', '60.90'),
 ('Dyett High School', '62.50'),
 ('Wendell Phillips Academy High School', '63.00'),
 ('Orr Academy High School', '66.30')]

In [28]:
#Q7

%sql select NAME_OF_SCHOOL as "School Name", Average_Student_Attendance as "Average Student Attendance" from SCHOOLS where cast(replace(Average_Student_Attendance,'%','') as decimal) < 70 order by AVERAGE_STUDENT_ATTENDANCE nulls last;

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Dyett High School', '62.50%'),
 ('Wendell Phillips Academy High School', '63.00%'),
 ('Orr Academy High School', '66.30%')]

In [44]:
#Q8

%sql select community_area_number, community_area_name, sum(college_enrollment) as "Total Enrollment" from SCHOOLS group by community_area_name, community_area_number ;

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[(1, 'ROGERS PARK', 4068),
 (2, 'WEST RIDGE', 8197),
 (3, 'UPTOWN', 4388),
 (4, 'LINCOLN SQUARE', 4132),
 (5, 'NORTH CENTER', 7541),
 (6, 'LAKE VIEW', 7055),
 (7, 'LINCOLN PARK', 5615),
 (8, 'NEAR NORTH SIDE', 3362),
 (9, 'EDISON PARK', 910),
 (10, 'NORWOOD PARK', 6469),
 (11, 'JEFFERSON PARK', 1755),
 (12, 'FOREST GLEN', 1431),
 (13, 'NORTH PARK', 4210),
 (14, 'ALBANY PARK', 6864),
 (15, 'PORTAGE PARK', 6954),
 (16, 'IRVING PARK', 7764),
 (17, 'DUNNING', 4568),
 (18, 'MONTCLARE', 1317),
 (19, 'BELMONT CRAGIN', 14386),
 (20, 'HERMOSA', 3975),
 (21, 'AVONDALE', 3640),
 (22, 'LOGAN SQUARE', 7351),
 (23, 'HUMBOLDT PARK', 8620),
 (24, 'WEST TOWN', 9429),
 (25, 'AUSTIN', 10933),
 (26, 'WEST GARFIELD PARK', 2622),
 (27, 'EAST GARFIELD PARK', 5337),
 (28, 'NEAR WEST SIDE', 7975),
 (29, 'NORTH LAWNDALE', 5146),
 (30, 'SOUTH LAWNDALE', 14793),
 (31, 'LOWER WEST SIDE', 7257),
 (32, 'LOOP', 871),
 (33, 'NEAR SOUTH SIDE', 1378),
 (34, 'ARMOUR SQUARE', 1458),
 (35, 'DOUGLAS', 4670),
 (36, 'OAKLAND', 140),
 (37, 'FULLER PARK', 531),
 (38, 'GRAND BOULEVARD', 2809),
 (39, 'KENWOOD', 4287),
 (40, 'WASHINGTON PARK', 2648),
 (41, 'HYDE PARK', 1930),
 (42, 'WOODLAWN', 4206),
 (43, 'SOUTH SHORE', 4543),
 (44, 'CHATHAM', 5042),
 (45, 'AVALON PARK', 1522),
 (46, 'SOUTH CHICAGO', 4043),
 (47, 'BURNSIDE', 549),
 (48, 'CALUMET HEIGHTS', 1568),
 (49, 'ROSELAND', 7020),
 (50, 'PULLMAN', 1620),
 (51, 'SOUTH DEERING', 1859),
 (52, 'EAST SIDE', 5305),
 (53, 'WEST PULLMAN', 3240),
 (54, 'RIVERDALE', 1547),
 (55, 'HEGEWISCH', 963),
 (56, 'GARFIELD RIDGE', 4552),
 (57, 'ARCHER HEIGHTS', 4823),
 (58, 'BRIGHTON PARK', 9647),
 (59, 'MCKINLEY PARK', 1552),
 (60, 'BRIDGEPORT', 3167),
 (61, 'NEW CITY', 7922),
 (62, 'WEST ELSDON', 3700),
 (63, 'GAGE PARK', 9915),
 (64, 'CLEARING', 2085),
 (65, 'WEST LAWN', 4207),
 (66, 'CHICAGO LAWN', 7086),
 (67, 'WEST ENGLEWOOD', 5946),
 (68, 'ENGLEWOOD', 6832),
 (69, 'GREATER GRAND CROSSING', 4051),
 (70, 'ASHBURN', 6483),
 (71, 'AUBURN GRESHAM', 4175),
 (72, 'BEVERLY', 1636),
 (73, 'WASHINGTON HEIGHTS', 4006),
 (74, 'MOUNT GREENWOOD', 2091),
 (75, 'MORGAN PARK', 3271),
 (76, 'OHARE', 786),
 (77, 'EDGEWATER', 4600)]

In [53]:
#Q9

%sql select community_area_number, community_area_name, sum(college_enrollment) as "Total Enrollment" from SCHOOLS group by community_area_name, community_area_number order by "Total Enrollment"

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[(36, 'OAKLAND', 140),
 (37, 'FULLER PARK', 531),
 (47, 'BURNSIDE', 549),
 (76, 'OHARE', 786),
 (32, 'LOOP', 871),
 (9, 'EDISON PARK', 910),
 (55, 'HEGEWISCH', 963),
 (18, 'MONTCLARE', 1317),
 (33, 'NEAR SOUTH SIDE', 1378),
 (12, 'FOREST GLEN', 1431),
 (34, 'ARMOUR SQUARE', 1458),
 (45, 'AVALON PARK', 1522),
 (54, 'RIVERDALE', 1547),
 (59, 'MCKINLEY PARK', 1552),
 (48, 'CALUMET HEIGHTS', 1568),
 (50, 'PULLMAN', 1620),
 (72, 'BEVERLY', 1636),
 (11, 'JEFFERSON PARK', 1755),
 (51, 'SOUTH DEERING', 1859),
 (41, 'HYDE PARK', 1930),
 (64, 'CLEARING', 2085),
 (74, 'MOUNT GREENWOOD', 2091),
 (26, 'WEST GARFIELD PARK', 2622),
 (40, 'WASHINGTON PARK', 2648),
 (38, 'GRAND BOULEVARD', 2809),
 (60, 'BRIDGEPORT', 3167),
 (53, 'WEST PULLMAN', 3240),
 (75, 'MORGAN PARK', 3271),
 (8, 'NEAR NORTH SIDE', 3362),
 (21, 'AVONDALE', 3640),
 (62, 'WEST ELSDON', 3700),
 (20, 'HERMOSA', 3975),
 (73, 'WASHINGTON HEIGHTS', 4006),
 (46, 'SOUTH CHICAGO', 4043),
 (69, 'GREATER GRAND CROSSING', 4051),
 (1, 'ROGERS PARK', 4068),
 (4, 'LINCOLN SQUARE', 4132),
 (71, 'AUBURN GRESHAM', 4175),
 (42, 'WOODLAWN', 4206),
 (65, 'WEST LAWN', 4207),
 (13, 'NORTH PARK', 4210),
 (39, 'KENWOOD', 4287),
 (3, 'UPTOWN', 4388),
 (43, 'SOUTH SHORE', 4543),
 (56, 'GARFIELD RIDGE', 4552),
 (17, 'DUNNING', 4568),
 (77, 'EDGEWATER', 4600),
 (35, 'DOUGLAS', 4670),
 (57, 'ARCHER HEIGHTS', 4823),
 (44, 'CHATHAM', 5042),
 (29, 'NORTH LAWNDALE', 5146),
 (52, 'EAST SIDE', 5305),
 (27, 'EAST GARFIELD PARK', 5337),
 (7, 'LINCOLN PARK', 5615),
 (67, 'WEST ENGLEWOOD', 5946),
 (10, 'NORWOOD PARK', 6469),
 (70, 'ASHBURN', 6483),
 (68, 'ENGLEWOOD', 6832),
 (14, 'ALBANY PARK', 6864),
 (15, 'PORTAGE PARK', 6954),
 (49, 'ROSELAND', 7020),
 (6, 'LAKE VIEW', 7055),
 (66, 'CHICAGO LAWN', 7086),
 (31, 'LOWER WEST SIDE', 7257),
 (22, 'LOGAN SQUARE', 7351),
 (5, 'NORTH CENTER', 7541),
 (16, 'IRVING PARK', 7764),
 (61, 'NEW CITY', 7922),
 (28, 'NEAR WEST SIDE', 7975),
 (2, 'WEST RIDGE', 8197),
 (23, 'HUMBOLDT PARK', 8620),
 (24, 'WEST TOWN', 9429),
 (58, 'BRIGHTON PARK', 9647),
 (63, 'GAGE PARK', 9915),
 (25, 'AUSTIN', 10933),
 (19, 'BELMONT CRAGIN', 14386),
 (30, 'SOUTH LAWNDALE', 14793)]

In [60]:
#Q10
%sql select hardship_index from  CHICAGO_SOCIOECONOMIC_DATA C, SCHOOLS S where C.ca=S.community_area_number and S.college_enrollment=4368;

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[(6.0,)]

In [56]:
#Q11
%sql select ca, community_area_name, hardship_index from chicago_socioeconomic_data \
   where ca in \
   ( select community_area_number from schools order by college_enrollment desc limit 1 )

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[(5.0, 'North Center', 6.0)]

 * ibm_db_sa://xsc80456:***@dashdb-txn-sbox-yp-dal09-03.services.dal.bluemix.net:50000/BLUDB
Done.

[(6.0,)]